server:
  port: 8000
spring:
  application:
    name: provider-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ #http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    preferIpAddress: true