server:
  port: 8050
spring:
  application:
    name: api-gateway

# routes to serviceId
zuul.routes.api-a.path: /user/**
zuul.routes.api-a.serviceId: provider-user

zuul.routes.api-b.path: /product/**
zuul.routes.api-b.serviceId: provider-product

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/  #http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    hostname: gateway          # 此处，preferIpAddress不设置或者设为false，不能设为true，否则影响turbine的测试。turbine存在的问题：eureka.instance.hostname一致时只能检测到一个节点，会造成turbine数据不完整
